import AboutContent from "./AboutContent";

export const metadata = {
  title: "About | Lloyd Butay – Full stack Developer",
  description: "Generated by create next app",
};

export default function About() {
  return <AboutContent />;
}
